feat(useAsyncStoryblok): Allow SSR SSG generation by default
storyblok/storyblok-nuxt pull request #205
Opened 2022-09-15 12:43 UTC by Dawntraoz

Changes:

- Create `useAsyncStoryblok` composable using `useAsyncData` and `useState` for static and server builds.
- Add autoImportDir for the new `composables` folder.
- Update README.
- Use the composable in the playground by default.
- Update nuxt commands.

2022-09-16 11:39 UTC, alexjoverm requested changes
Awesome PR @Dawntraoz ! The only thing I would say is that IMO we need to replace `useStoryblok` by `useAsyncStoryblok` in the whole Readme (including https://github.com/storyblok/storyblok-nuxt#2-getting-storyblok-stories-and-listen-to-visual-editor-events) as it's the new default they should use which works SSR as well

2022-09-17 11:40 UTC, Dawntraoz commented
> Awesome PR @Dawntraoz ! The only thing I would say is that IMO we need to replace `useStoryblok` by `useAsyncStoryblok` in the whole Readme (including https://github.com/storyblok/storyblok-nuxt#2-getting-storyblok-stories-and-listen-to-visual-editor-events) as it's the new default they should use which works SSR as well

Done ☑️

2022-09-19 12:30 UTC, manuelschroederdev requested changes
All looks great to me except of what I pointed out in the readme 🙂

2022-09-20 09:35 UTC, Dawntraoz commented
@manuelschroederdev @alexjoverm I follow your tips, can you double-check the docs?

2022-09-20 09:42 UTC, manuelschroederdev approved these changes

2022-09-20 13:28 UTC, merged