Fix autoImports under nuxt v3.0.0
storyblok/storyblok-nuxt pull request #235
Opened 2022-11-16 16:33 UTC by chrisnoden

Responding to deprecations warned in earlier release candidates but which now have caused the storyblok-nuxt module to break the nuxt build

2022-11-16 21:11 UTC, alvarosabu approved these changes
I checked on locally, it does solve the issue

2022-11-17 08:19 UTC, RobertWade requested changes
You can just rename the import to addImports and change this in the whole file. Same goes with addAutoImportDir can be renamed to addImportDir

2022-11-17 09:11 UTC, patrykkurzeja91 commented on lib/src/module.js
> +  addImports as addAutoImport,
```suggestion
  addImports,
  addImportsDir
```

2022-11-17 09:15 UTC, patrykkurzeja91 commented
@chrisnoden please do not change formatting for this file. it is unnecessary.

2022-11-17 11:00 UTC, RobertWade approved these changes
Looks good to mee

2022-11-17 12:06 UTC, patrykkurzeja91 approved these changes
LGTM

2022-11-28 18:08 UTC, Dawntraoz commented
Hi folks 👋
I was checking the PRs, and it seems that @alexjoverm didn't see this one while working on the fix for that -> https://github.com/storyblok/storyblok-nuxt/commit/545971dcd092fc43e0109c9182fda8e20cc33d2b!

Thanks a lot for the PR and the implementation 💜 Feel free to create more PRs if you found any other issues/warnings, please. We will love to have you as a contributor!

PS: As it's already there, I will close this one. But next time, you can tag or add as reviewers @alexjoverm or me so that we can be notified and merge it in time 🫂

2022-11-28 18:08 UTC, closed without merging