Nuxt Devtools integration
storyblok/storyblok-nuxt pull request #333
Opened 2023-03-20 10:34 UTC by markus-gx

Added basic integration for Storyblok inside nuxt-devtools. 

![image](https://user-images.githubusercontent.com/16301998/226314904-72be726b-a65a-4c91-8342-87b7c3ea5c2a.png)

2023-03-27 18:05 UTC, Dawntraoz approved these changes
What an excellent idea @markus-gx 😍

2023-03-27 18:53 UTC, markus-gx commented
> What an excellent idea @markus-gx 😍

Possibly enhancements in the feature could be to automatically show the corresponding space/page inside Storyblok without the need to navigate in an iframe. But Devtools is not yet capable to do that (Adjusting iFrame Routes based on current route on client side). 🤔

2023-03-28 09:19 UTC, alexjoverm requested changes
@markus-gx I love your creativity, so cool DX :) Added couple of minor comments and we're good to go

2023-03-28 09:19 UTC, alexjoverm commented on package.json
> +    "@nuxt/devtools": "^0.2.5",
@markus-gx I believe this devDep should go into playground/package.json

2023-03-28 09:19 UTC, alexjoverm commented on README.md
> +If you want to use Storyblok inside `nuxt-devtools` you can use the option `devtools`.
@markus-gx can we add a note on the lines of "if you enable the devtools option, make sure to have installed the `@nuxt/devtools` module and enable it on your nuxt config"

If you feel like you need extra space, we can create a small h3 section for the devtools

2023-04-05 16:04 UTC, alexjoverm approved these changes

2023-04-05 16:05 UTC, alexjoverm commented
@markus-gx I approved it, but it has some conflicts to resolve. I think if you merge latest `main` should be fixed. As soon as you push it, we'll merge! Really cool stuff, thank you

2023-04-06 15:41 UTC, merged

2023-04-06 15:41 UTC, alexjoverm commented
Amazing! Kudos @markus-gx

2023-08-21 09:46 UTC, samuells commented
👏 👏 👏  thank you @markus-gx